# 1. 创建张量

In [2]:
import torch

In [3]:
# 创建张量
x = torch.arange(1,11)
print(x)
print(x.shape)
print(type(x))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10])
<class 'torch.Tensor'>


In [4]:
# 使用特定的值创建张量
x = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

# 2. 元素级别的运算

In [5]:
# 元素级别的运算
x = torch.arange(1,5)
y = torch.rand(size=(4,))

# 矩阵对应元素+,-,*,/,^
x+y, x-y, x*y, x/y, x**y

(tensor([1.6849, 2.5263, 3.2807, 4.2003]),
 tensor([0.3151, 1.4737, 2.7193, 3.7997]),
 tensor([0.6849, 1.0525, 0.8421, 0.8013]),
 tensor([ 1.4600,  3.8004, 10.6877, 19.9685]),
 tensor([1.0000, 1.4402, 1.3612, 1.3201]))

# 3. 张量拼接

In [6]:
x = torch.arange(1,13).reshape(3,4)
y = torch.randint(low=1,high=13,size=(3,4))
x,y

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([[ 1,  3,  9,  2],
         [ 2,  2,  3, 11],
         [ 6,  9, 12,  1]]))

In [7]:
torch.cat((x,y),dim=0)  # dim=0:按行进行拼接

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  3,  9,  2],
        [ 2,  2,  3, 11],
        [ 6,  9, 12,  1]])

In [8]:
torch.cat((x,y),dim=1) # dim=1:按列进行拼接

tensor([[ 1,  2,  3,  4,  1,  3,  9,  2],
        [ 5,  6,  7,  8,  2,  2,  3, 11],
        [ 9, 10, 11, 12,  6,  9, 12,  1]])

<img src="https://zyc-learning-1309954661.cos.ap-nanjing.myqcloud.com/machine-learning-pic/2020081016403863.png" alt="二维矩阵" style="zoom: 50%;" />

# 3. 张量中的数据统计

In [10]:
x = torch.arange(1,13).reshape(3,4)
x, x.sum(), x.max(), x.min()

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor(78),
 tensor(12),
 tensor(1))

# 4. 张量运算中的广播机制

In [13]:
x = torch.arange(3).reshape(3,1)
y = torch.arange(2).reshape(1,2)
x,y,x+y

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

![image-20240410155253290](https://zyc-learning-1309954661.cos.ap-nanjing.myqcloud.com/machine-learning-pic/image-20240410155253290.png)

# 5. 元素访问

In [29]:
x = torch.arange(1,13).reshape(3,4)
x, \
x[-1,:], \
x[:,-1], \
x[0:3:2,:]  # 0~2行，每隔两行访问

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([ 9, 10, 11, 12]),
 tensor([ 4,  8, 12]),
 tensor([[ 1,  2,  3,  4],
         [ 9, 10, 11, 12]]))

# 6. 元素修改

In [33]:
x = torch.zeros(size=(5,5))
x[1:2, 1:3]=1   # 赋值可以直接改变值
x

tensor([[0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# 7. 运算前后变量在内存中的变化

In [37]:
x = torch.arange(10)
print('previous:', id(x))
x = x + 1
print('current:', id(x))

previous: 2379028033072
current: 2379028030032


上述代码表示：执行`x = x + 1`操作后，`x`在内存中以及不是原来的`x`了

In [38]:
x = torch.arange(10)
print('previous:', id(x))
x += 1
print('current:', id(x))

previous: 2379028085184
current: 2379028085184


但是，使用`x += 1`，`x`在内存中的位置不变

# 8. torch和numpy的转化

In [40]:
import numpy as np

In [45]:
# 用numpy数组创建tensor
x = np.array([[31,4,1,31],[13,31,4,1],[4,2,56,1]])
tensor = torch.tensor(x)
tensor, type(tensor)

(tensor([[31,  4,  1, 31],
         [13, 31,  4,  1],
         [ 4,  2, 56,  1]], dtype=torch.int32),
 torch.Tensor)

In [46]:
# 用tensor获取对应的numpy数组
x = torch.tensor([[31,4,1,31],[13,31,4,1],[4,2,56,1]])
ndarray = x.numpy()
ndarray, type(ndarray)

(array([[31,  4,  1, 31],
        [13, 31,  4,  1],
        [ 4,  2, 56,  1]], dtype=int64),
 numpy.ndarray)