In [2]:
import torch

# 1. 矩阵克隆

等号赋值相当于起别名，通过别名修改矩阵，原矩阵也会改变

In [3]:
A = torch.tensor([[1,2,3],[4,5,6]])
B = A

print(id(B)==id(A))
B[1,2]=100
B,A

True


(tensor([[  1,   2,   3],
         [  4,   5, 100]]),
 tensor([[  1,   2,   3],
         [  4,   5, 100]]))

使用`clone`函数，才会另外创建一个相同的矩阵

In [4]:
A = torch.tensor([[1,2,3],[4,5,6]])
B = A.clone()

print(id(B)==id(A))
B[1,2]=100
B,A

False


(tensor([[  1,   2,   3],
         [  4,   5, 100]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

# 2. 求最小值（最大值/平均值/求和）

以`shape=(2,2,3)`的矩阵为例

<img src="https://zyc-learning-1309954661.cos.ap-nanjing.myqcloud.com/machine-learning-pic/1712843202154-screenshot.png" alt="1712843202154-screenshot" style="zoom:67%;" />

In [25]:
x = torch.tensor([[[3,6,4],[3,3,1]],[[4,3,6],[3,1,0]]])
x.min(dim=0).values, x.min(dim=1).values, x.min(dim=2).values

(tensor([[3, 3, 4],
         [3, 1, 0]]),
 tensor([[3, 3, 1],
         [3, 1, 0]]),
 tensor([[3, 1],
         [3, 0]]))

把`(2,2,3)`矩阵想象成2个2*3的矩阵上下堆叠起来。

- `dim=0`指的是第一个‘2’，表示有2个2\*3矩阵，第0个2\*3矩阵在上，第1个在下，从编号小的往大的方向看；
- `dim=1`指的是第二个‘2’，按二维矩阵行递增的方向看
- `dim=2`指的是‘3’，按二维矩阵列递增的方向看

`dim`还可以取值为一个列表（只适用于`mean`和`sum`）：

In [36]:
x = torch.tensor([[[3,6,4],[3,3,1]],[[4,3,6],[3,1,0]]],dtype=torch.float32)
x.sum(dim=[0,1])        # 先按图中dim=0的方向相加，再按dim=1的方向相加

tensor([13., 13., 11.])